// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using handytool_api.Data;

#nullable disable

namespace handytool_api.Data.Migrations
{
    [DbContext(typeof(HandyToolDbContext))]
    [Migration("20260905104337_AddRecordCompanyOwnershipAndRevision")]
    partial class AddRecordCompanyOwnershipAndRevision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("handytool_api.Models.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 4L, null, null, null, null, null);

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AccountTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountTypes_AccessLevel", "\"AccessLevel\" BETWEEN 1 AND 3");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = 1,
                            Code = "free",
                            Name = "Free"
                        },
                        new
                        {
                            Id = 2,
                            AccessLevel = 2,
                            Code = "light",
                            Name = "Light"
                        },
                        new
                        {
                            Id = 3,
                            AccessLevel = 3,
                            Code = "full",
                            Name = "Full"
                        });
                });

            modelBuilder.Entity("handytool_api.Models.AnalyticsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Language");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ClientId", "Timestamp");

                    b.HasIndex("SessionId", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AnalyticsEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnalyticsEvents_ActiveSeconds_NonNegative", "\"ActiveSeconds\" IS NULL OR \"ActiveSeconds\" >= 0");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.AuthThrottle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LastFailedAt");

                    b.HasIndex("Scope", "KeyHash")
                        .IsUnique();

                    b.ToTable("AuthThrottles", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.BooleanField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("BooleanFields", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.ChecklistField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumSelections")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumSelections")
                        .HasColumnType("integer");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("ChecklistFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChecklistFields_Settings", "(\"MinimumSelections\" IS NULL OR \"MaximumSelections\" IS NULL OR \"MinimumSelections\" <= \"MaximumSelections\") AND (\"MinimumSelections\" IS NULL OR \"MinimumSelections\" >= 0) AND (\"MaximumSelections\" IS NULL OR \"MaximumSelections\" >= 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.CollectionField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumItems")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumItems")
                        .HasColumnType("integer");

                    b.HasKey("FieldDefinitionId");

                    b.HasIndex("ItemDefinitionId");

                    b.ToTable("CollectionFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionFields_Settings", "(\"MinimumItems\" IS NULL OR \"MaximumItems\" IS NULL OR \"MinimumItems\" <= \"MaximumItems\") AND (\"MinimumItems\" IS NULL OR \"MinimumItems\" >= 0) AND (\"MaximumItems\" IS NULL OR \"MaximumItems\" >= 0) AND (\"ItemDefinitionId\" <> \"FieldDefinitionId\")");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.CompanyAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SeatLimit")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("CompanyAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyAccounts_SeatLimit", "\"SeatLimit\" >= 0");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.DateField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("MaximumDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MinimumDate")
                        .HasColumnType("date");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("DateFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_DateFields_Settings", "(\"MinimumDate\" IS NULL OR \"MaximumDate\" IS NULL OR \"MinimumDate\" <= \"MaximumDate\")");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.DateTimeField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MaximumDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MinimumDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("DateTimeFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_DateTimeFields_Settings", "(\"MinimumDateTime\" IS NULL OR \"MaximumDateTime\" IS NULL OR \"MinimumDateTime\" <= \"MaximumDateTime\")");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.DecimalField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Maximum")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Minimum")
                        .HasColumnType("numeric");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("Step")
                        .HasColumnType("numeric");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("DecimalFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_DecimalFields_Settings", "(\"Minimum\" IS NULL OR \"Maximum\" IS NULL OR \"Minimum\" <= \"Maximum\") AND (\"Step\" IS NULL OR \"Step\" > 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.DropdownField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("DropdownFields", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.FieldDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ObjectDefinitionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionId");

                    b.HasIndex("ObjectDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("FieldDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_FieldDefinitions_FieldType", "\"FieldType\" BETWEEN 1 AND 16");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.FieldDefinitionTranslation", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("FieldDefinitionId", "LanguageCode");

                    b.ToTable("FieldDefinitionTranslations", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.FieldOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("FieldDefinitionId", "Value")
                        .IsUnique();

                    b.ToTable("FieldOptions", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.FieldOptionTranslation", b =>
                {
                    b.Property<long>("FieldOptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("FieldOptionId", "LanguageCode");

                    b.ToTable("FieldOptionTranslations", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.IntegerField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Maximum")
                        .HasColumnType("bigint");

                    b.Property<long?>("Minimum")
                        .HasColumnType("bigint");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long?>("Step")
                        .HasColumnType("bigint");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("IntegerFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegerFields_Settings", "(\"Minimum\" IS NULL OR \"Maximum\" IS NULL OR \"Minimum\" <= \"Maximum\") AND (\"Step\" IS NULL OR \"Step\" > 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.LongTextField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumLength")
                        .HasColumnType("integer");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Rows")
                        .HasColumnType("integer");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("LongTextFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_LongTextFields_Settings", "(\"MinimumLength\" IS NULL OR \"MaximumLength\" IS NULL OR \"MinimumLength\" <= \"MaximumLength\") AND (\"MinimumLength\" IS NULL OR \"MinimumLength\" >= 0) AND (\"MaximumLength\" IS NULL OR \"MaximumLength\" >= 0) AND (\"Rows\" IS NULL OR \"Rows\" > 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.MarkdownField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumLength")
                        .HasColumnType("integer");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("MarkdownFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarkdownFields_Settings", "(\"MinimumLength\" IS NULL OR \"MaximumLength\" IS NULL OR \"MinimumLength\" <= \"MaximumLength\") AND (\"MinimumLength\" IS NULL OR \"MinimumLength\" >= 0) AND (\"MaximumLength\" IS NULL OR \"MaximumLength\" >= 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.MasterCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MasterCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CreatedDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default category for definitions awaiting classification.",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("handytool_api.Models.MasterCategoryTranslation", b =>
                {
                    b.Property<long>("MasterCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MasterCategoryId", "LanguageCode");

                    b.ToTable("MasterCategoryTranslations", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.MultiSelectField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumSelections")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumSelections")
                        .HasColumnType("integer");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("MultiSelectFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_MultiSelectFields_Settings", "(\"MinimumSelections\" IS NULL OR \"MaximumSelections\" IS NULL OR \"MinimumSelections\" <= \"MaximumSelections\") AND (\"MinimumSelections\" IS NULL OR \"MinimumSelections\" >= 0) AND (\"MaximumSelections\" IS NULL OR \"MaximumSelections\" >= 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.ObjectDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("MasterCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RequiredAccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long?>("SubcategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MasterCategoryId");

                    b.HasIndex("CreatedByUserId", "Name")
                        .IsUnique();

                    b.HasIndex("SubcategoryId", "MasterCategoryId");

                    b.ToTable("ObjectDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ObjectDefinitions_CompanyVisibility", "(\"Visibility\" = 1 AND \"CompanyId\" IS NOT NULL) OR (\"Visibility\" IN (0, 2) AND \"CompanyId\" IS NULL)");

                            t.HasCheckConstraint("CK_ObjectDefinitions_RequiredAccessLevel", "\"RequiredAccessLevel\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_ObjectDefinitions_Visibility", "\"Visibility\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.ObjectDefinitionTranslation", b =>
                {
                    b.Property<long>("ObjectDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ObjectDefinitionId", "LanguageCode");

                    b.ToTable("ObjectDefinitionTranslations", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.ObjectField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReferencedObjectDefinitionId")
                        .HasColumnType("bigint");

                    b.HasKey("FieldDefinitionId");

                    b.HasIndex("ReferencedObjectDefinitionId");

                    b.ToTable("ObjectFields", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.ObjectRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ObjectDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<JsonDocument>("Values")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ObjectDefinitionId");

                    b.ToTable("ObjectRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_ObjectRecords_Revision", "\"Revision\" >= 1");

                            t.HasCheckConstraint("CK_ObjectRecords_Values_IsObject", "jsonb_typeof(\"Values\") = 'object'");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.RadioGroupField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("RadioGroupFields", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.RangeField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Maximum")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Minimum")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Step")
                        .HasColumnType("numeric");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("RangeFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_RangeFields_Settings", "(\"Minimum\" IS NULL OR \"Maximum\" IS NULL OR \"Minimum\" <= \"Maximum\") AND (\"Step\" IS NULL OR \"Step\" > 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.ShortTextField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumLength")
                        .HasColumnType("integer");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("ShortTextFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShortTextFields_Settings", "(\"MinimumLength\" IS NULL OR \"MaximumLength\" IS NULL OR \"MinimumLength\" <= \"MaximumLength\") AND (\"MinimumLength\" IS NULL OR \"MinimumLength\" >= 0) AND (\"MaximumLength\" IS NULL OR \"MaximumLength\" >= 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.Subcategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("MasterCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MasterCategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Subcategories", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.SubcategoryTranslation", b =>
                {
                    b.Property<long>("SubcategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SubcategoryId", "LanguageCode");

                    b.ToTable("SubcategoryTranslations", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.TimeField", b =>
                {
                    b.Property<long>("FieldDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly?>("MaximumTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MinimumTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("StepSeconds")
                        .HasColumnType("integer");

                    b.HasKey("FieldDefinitionId");

                    b.ToTable("TimeFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimeFields_Settings", "(\"MinimumTime\" IS NULL OR \"MaximumTime\" IS NULL OR \"MinimumTime\" <= \"MaximumTime\") AND (\"StepSeconds\" IS NULL OR \"StepSeconds\" > 0)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.TrackingClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientType");

                    b.HasIndex("LastSeenDate");

                    b.ToTable("TrackingClients", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.TrackingClientUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstIdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastIdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClientId", "UserId")
                        .IsUnique();

                    b.ToTable("TrackingClientUsers", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.TrackingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "LastActivityAt");

                    b.ToTable("TrackingSessions", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AccountTypeId")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CompanyRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_CompanyMembership", "(\"CompanyId\" IS NULL AND \"CompanyRole\" IS NULL AND \"AccountTypeId\" IS NOT NULL) OR (\"CompanyId\" IS NOT NULL AND \"CompanyRole\" IS NOT NULL AND \"CompanyRole\" IN (0, 1, 2) AND \"AccountTypeId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("handytool_api.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresDate");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedDate");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("handytool_api.Models.AnalyticsEvent", b =>
                {
                    b.HasOne("handytool_api.Models.TrackingClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.TrackingSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("handytool_api.Models.BooleanField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("BooleanField")
                        .HasForeignKey("handytool_api.Models.BooleanField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.ChecklistField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("ChecklistField")
                        .HasForeignKey("handytool_api.Models.ChecklistField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.CollectionField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("CollectionField")
                        .HasForeignKey("handytool_api.Models.CollectionField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.FieldDefinition", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldDefinition");

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.CompanyAccount", b =>
                {
                    b.HasOne("handytool_api.Models.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("handytool_api.Models.DateField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("DateField")
                        .HasForeignKey("handytool_api.Models.DateField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.DateTimeField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("DateTimeField")
                        .HasForeignKey("handytool_api.Models.DateTimeField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.DecimalField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("DecimalField")
                        .HasForeignKey("handytool_api.Models.DecimalField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.DropdownField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("DropdownField")
                        .HasForeignKey("handytool_api.Models.DropdownField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.FieldDefinition", b =>
                {
                    b.HasOne("handytool_api.Models.ObjectDefinition", "ObjectDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ObjectDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.FieldDefinitionTranslation", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithMany("Translations")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.FieldOption", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.FieldOptionTranslation", b =>
                {
                    b.HasOne("handytool_api.Models.FieldOption", "FieldOption")
                        .WithMany("Translations")
                        .HasForeignKey("FieldOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldOption");
                });

            modelBuilder.Entity("handytool_api.Models.IntegerField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("IntegerField")
                        .HasForeignKey("handytool_api.Models.IntegerField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.LongTextField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("LongTextField")
                        .HasForeignKey("handytool_api.Models.LongTextField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.MarkdownField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("MarkdownField")
                        .HasForeignKey("handytool_api.Models.MarkdownField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.MasterCategoryTranslation", b =>
                {
                    b.HasOne("handytool_api.Models.MasterCategory", "MasterCategory")
                        .WithMany("Translations")
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCategory");
                });

            modelBuilder.Entity("handytool_api.Models.MultiSelectField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("MultiSelectField")
                        .HasForeignKey("handytool_api.Models.MultiSelectField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.ObjectDefinition", b =>
                {
                    b.HasOne("handytool_api.Models.CompanyAccount", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("handytool_api.Models.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.MasterCategory", "MasterCategory")
                        .WithMany()
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId", "MasterCategoryId")
                        .HasPrincipalKey("Id", "MasterCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");

                    b.Navigation("MasterCategory");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("handytool_api.Models.ObjectDefinitionTranslation", b =>
                {
                    b.HasOne("handytool_api.Models.ObjectDefinition", "ObjectDefinition")
                        .WithMany("Translations")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.ObjectField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("ObjectField")
                        .HasForeignKey("handytool_api.Models.ObjectField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.ObjectDefinition", "ReferencedObjectDefinition")
                        .WithMany()
                        .HasForeignKey("ReferencedObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldDefinition");

                    b.Navigation("ReferencedObjectDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.ObjectRecord", b =>
                {
                    b.HasOne("handytool_api.Models.CompanyAccount", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("handytool_api.Models.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.ObjectDefinition", "ObjectDefinition")
                        .WithMany("Records")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ObjectDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.RadioGroupField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("RadioGroupField")
                        .HasForeignKey("handytool_api.Models.RadioGroupField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.RangeField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("RangeField")
                        .HasForeignKey("handytool_api.Models.RangeField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.ShortTextField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("ShortTextField")
                        .HasForeignKey("handytool_api.Models.ShortTextField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.Subcategory", b =>
                {
                    b.HasOne("handytool_api.Models.MasterCategory", "MasterCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterCategory");
                });

            modelBuilder.Entity("handytool_api.Models.SubcategoryTranslation", b =>
                {
                    b.HasOne("handytool_api.Models.Subcategory", "Subcategory")
                        .WithMany("Translations")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("handytool_api.Models.TimeField", b =>
                {
                    b.HasOne("handytool_api.Models.FieldDefinition", "FieldDefinition")
                        .WithOne("TimeField")
                        .HasForeignKey("handytool_api.Models.TimeField", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("handytool_api.Models.TrackingClientUser", b =>
                {
                    b.HasOne("handytool_api.Models.TrackingClient", "Client")
                        .WithMany("Users")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("handytool_api.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("handytool_api.Models.TrackingSession", b =>
                {
                    b.HasOne("handytool_api.Models.TrackingClient", "Client")
                        .WithMany("Sessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("handytool_api.Models.UserAccount", b =>
                {
                    b.HasOne("handytool_api.Models.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("handytool_api.Models.CompanyAccount", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountType");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("handytool_api.Models.UserSession", b =>
                {
                    b.HasOne("handytool_api.Models.UserAccount", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("handytool_api.Models.CompanyAccount", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("handytool_api.Models.FieldDefinition", b =>
                {
                    b.Navigation("BooleanField");

                    b.Navigation("ChecklistField");

                    b.Navigation("CollectionField");

                    b.Navigation("DateField");

                    b.Navigation("DateTimeField");

                    b.Navigation("DecimalField");

                    b.Navigation("DropdownField");

                    b.Navigation("IntegerField");

                    b.Navigation("LongTextField");

                    b.Navigation("MarkdownField");

                    b.Navigation("MultiSelectField");

                    b.Navigation("ObjectField");

                    b.Navigation("Options");

                    b.Navigation("RadioGroupField");

                    b.Navigation("RangeField");

                    b.Navigation("ShortTextField");

                    b.Navigation("TimeField");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("handytool_api.Models.FieldOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("handytool_api.Models.MasterCategory", b =>
                {
                    b.Navigation("Subcategories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("handytool_api.Models.ObjectDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("handytool_api.Models.Subcategory", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("handytool_api.Models.TrackingClient", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("handytool_api.Models.UserAccount", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
